### ISSUE TITLE
Q: "probe: Login code was 404, expected 200"

### ISSUE THREAD

**Issue by DirkFries** [bluecmd/spectrum_virtualize_exporter#11]
Hi there,

still wrestling a little with the exporter.

So I got my configuration file like this:

```
https://v3700:443:
  user: user
  password: password
```

and I call  the exporter like this

`http://host-that-runs-the-exporter:9747/probe?target=https://v3700:443`

and I get

`Probe request rejected; error is: Login code was 404, expected 200`

I tried to configure the exporter with all ports that the v3700 has opened, but on every port I get the same error. Of course I also doublechecked the credentials

Because of the 404 I think that I have to add something to the url, but I have no idea what.
Maybe someone has a hint?

Bye, Dirk

**Comment by bluecmd** [comment]
What version are you running on your V3700? On my V7000 the correct port is 7443, FWIW.

**Comment by DirkFries** [comment]
I run 7.8.1.14.
Just tried port 7443 - no open port

**Comment by bluecmd** [comment]
I am running 8.3.x.x, so maybe you need a newer software to use this exporter. That's my only guess, sorry.

**Comment by DirkFries** [comment]
Ok, that is probably the cause.
Thanks a lot for your support !
